### ISSUE TITLE
I am interested your tracking demo

### ISSUE THREAD

**Issue by ghost** [mythly/FAR#1]
could you have a paper about your tracking demo?Thx

**Comment by mythly** [comment]
Thanks for your interest!
There is a paper about this repo, which is just submitted to a conference.
Due to the double blind policy, I'm sorry that I cannot provide the paper until the publication.

**Comment by ghost** [comment]
Ok,if your paper accepted,could you give me a link for paper?

**Comment by mythly** [comment]
Of course.

**Comment by mythly** [comment]
Of course.
